/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#111c2d",
        "tertiary-container": "#24292c",
        "secondary-fixed-dim": "#7bd0ff",
        outline: "#75777d",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "primary-container": "#1e293b",
        "on-surface-variant": "#45474c",
        "on-surface": "#0b1c30",
        "error-container": "#ffdad6",
        "on-secondary-container": "#004d6a",
        "primary-fixed-dim": "#bcc7de",
        "on-primary-container": "#8590a6",
        "inverse-primary": "#bcc7de",
        background: "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "secondary-container": "#40c2fd",
        "on-tertiary-fixed": "#171c1f",
        "outline-variant": "#c5c6cd",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#e5eeff",
        "on-primary-fixed-variant": "#3c475a",
        "on-secondary-fixed": "#001e2c",
        "on-error": "#ffffff",
        secondary: "#00668a",
        "on-background": "#0b1c30",
        "surface-tint": "#545f73",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#004c69",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#dfe3e7",
        "secondary-fixed": "#c4e7ff",
        "on-primary": "#ffffff",
        surface: "#f8f9ff",
        "tertiary-fixed-dim": "#c3c7cb",
        "on-tertiary-container": "#8b9094",
        "inverse-surface": "#213145",
        "primary-fixed": "#d8e3fb",
        "surface-bright": "#f8f9ff",
        tertiary: "#101517",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed-variant": "#43474b",
        "surface-dim": "#cbdbf5",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-low": "#eff4ff",
        primary: "#091426",
      },
      fontFamily: {
        h3: ["Inter"],
        h2: ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        h1: ["Inter"],
        "body-md": ["Inter"],
      },
    },
  },
  plugins: [],
};
