"""Add backup logs

Revision ID: 550cf7fa6dd0
Revises: ec676c69d590
Create Date: 2026-04-30 21:51:05.848162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550cf7fa6dd0'
down_revision: Union[str, Sequence[str], None] = 'ec676c69d590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_logs_id'), 'backup_logs', ['id'], unique=False)
    op.create_index(op.f('ix_backup_logs_snapshot_id'), 'backup_logs', ['snapshot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_logs_snapshot_id'), table_name='backup_logs')
    op.drop_index(op.f('ix_backup_logs_id'), table_name='backup_logs')
    op.drop_table('backup_logs')
    # ### end Alembic commands ###
