"""remove_backup_log_table

Revision ID: aab89732da24
Revises: e34fea57e70c
Create Date: 2026-05-09 23:44:58.645866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aab89732da24'
down_revision: Union[str, Sequence[str], None] = 'e34fea57e70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_logs_id'), table_name='backup_logs')
    op.drop_index(op.f('ix_backup_logs_snapshot_id'), table_name='backup_logs')
    op.drop_table('backup_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('backup_logs_pkey'))
    )
    op.create_index(op.f('ix_backup_logs_snapshot_id'), 'backup_logs', ['snapshot_id'], unique=True)
    op.create_index(op.f('ix_backup_logs_id'), 'backup_logs', ['id'], unique=False)
    # ### end Alembic commands ###
