"""Add floors to Hostel and Room

Revision ID: ec676c69d590
Revises: 7e25324ede80
Create Date: 2026-04-24 21:03:57.184115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec676c69d590'
down_revision: Union[str, Sequence[str], None] = '7e25324ede80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostels', sa.Column('total_floors', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('floor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'floor')
    op.drop_column('hostels', 'total_floors')
    # ### end Alembic commands ###
